name: build-windows

on:
  pull_request:
  push:
    branches:
      - master
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x

env:
  PYTHON_VERSION: 3.9
  FLAKY_TESTS: dontcare

jobs:
  build-windows-with-quic:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat experimental-quic

  build-windows-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat arm64
